### ISSUE TITLE
Why is DownloadButton delete method call limitDownloads?

### ISSUE THREAD

**Issue by ChauCM** [yringler/inside-app#101]
```
          if (download.status == DownloadTaskStatus.complete) {
            return buttonBuilder(Icons.delete,
                () async => await limitDownloads(downloader, limit: 1));
          }
```

Should it be `await downloader.remove(download.taskId)` to delete downloaded audio?

**Comment by yringler** [comment]
That does look like a mistake.
Check git history?
Or fix etc as you see fit, there will be testing and review before it's
merged to master

**Comment by yringler** [comment]
I'm pretty sure: I was testing out the limit functionality, and that was the easiest way to do it, and forgot to change back after
