### ISSUE TITLE
Add suggested content to the home page

### ISSUE THREAD

**Issue by efraimbart** [yringler/inside-app#106]
![image](https://user-images.githubusercontent.com/4070825/148070119-b481c97a-00d6-4cc3-a1a5-98f9d376a3a3.png)

**Comment by yringler** [comment]
Here is a new API endpoint that can be used to get today's tanya and hayom yom post ids:
https://insidechassidus.org/wp-json/ics_recurring_api/v1/daily

{"tanya_id":23941,"hayom_yom_id":20076}

Here is another API endpoint for the parsha category id:
https://insidechassidus.org/wp-json/ics_recurring_api/v1/category
sample output:
{"parsha":248}

**Comment by yringler** [comment]
Here is an API endpoint to get the featured categories (banner slider on homepage of site):
https://insidechassidus.org/wp-json/ics_slider_api/v1/featured
sample output:
{"title":"Chanuka","category":246,"image_url":"https:\/\/media.insidechassidus.org\/wp-content\/uploads\/20211125105910\/chanuka.gif","button_text":"Learn More"

**Comment by yringler** [comment]
popular posts:
https://insidechassidus.org/wp-json/ics_recurring_api/v1/category

returns an array, only value of objects we really need is the id

**Comment by yringler** [comment]
Question: where to put Parsha and Month categories?
Their categories, so I think I'd put them in same style as Popular and Recent,
Parsha
Month
Popular
Recent
