### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by yringler** [yringler/inside-app#23]
For now, I'm generating the icon using [app icon generator](https://appicon.co/#app-icon) from the [inside chassidus logo](https://insidechassidus.org/wp-content/uploads/inside-chassidus-org-png-1.png)

[AppIcons.zip](https://github.com/yringler/inside-app/files/3794070/AppIcons.zip)

**Comment by yringler** [comment]
[AppIcons.zip](https://github.com/yringler/inside-app/files/3794070/AppIcons.zip)

**Comment by levibait** [comment]
Here is the updated logo for us to use temporarily until we get the original SVG from them, at which point I can adjust it properly and make a permanent
[Temp-AppIcons.zip](https://github.com/yringler/inside-app/files/3795156/Temp-AppIcons.zip)
 icon.

**Comment by yringler** [comment]
Closed - we have a very nice purple icon...
